{
  Q00: 'http://cid.oxfordjournals.org/content/52/4/e56.full',
  Q02.47: 'http://www.annals.org/content/119/4/270.full',
  Q02.49: 'http://jcm.asm.org/content/45/11/3546.full',
  Q02.50: 'http://cid.oxfordjournals.org/content/38/12/1724.full',
  Q02.51: 'http://www.annals.org/content/131/9/641.1.full',
  Q02.52: 'http://cid.oxfordjournals.org/content/23/1/40.short',
  Q02.55: 'http://www.springerlink.com/content/7uxg8uybjry9hu61/fulltext.html',
  Q02.56: 'http://onlinelibrary.wiley.com/doi/10.1111/j.1600-0609.2004.00387.x/full',
  Q02.57: 'http://www.springerlink.com/content/f5754730675j1643/fulltext.html',
  Q10.292: 'http://www.ejcancer.info/article/S0959-8049(06)00391-1/fulltext',
  Q10.2922010: 'http://www.ncbi.nlm.nih.gov/pubmed/21095116',
  Q10.293: 'http://jco.ascopubs.org/content/24/19/3187.full',
  Q10.294: 'http://www.jnccn.org/content/7/1/64.short',
  Q10.295: 'http://jco.ascopubs.org/content/24/19/2991.full',
  Q10.296: 'http://jco.ascopubs.org/content/26/2/290.full',
  Q10.297: 'http://jco.ascopubs.org/content/24/19/2975',
  Q10.298: 'http://onlinelibrary.wiley.com/doi/10.1002/cncr.21847/full',
  Q10.299: 'http://www.croh-online.com/article/S1040-8428(09)00005-5/fulltext',
  Q10.301: 'http://www.annals.org/content/121/7/492.full',
  Q10.303: 'http://jnci.oxfordjournals.org/content/93/1/31.full',
  content1: 'http://www.sciencedirect.com/science/article/pii/S1386653210000156',
  content10: 'http://www.sciencedirect.com/science/article/pii/S0959804910010294',
  content11: 'http://www.sciencedirect.com/science/article/pii/S1083879111010275',
  content12: 'http://www.sciencedirect.com/science/article/pii/S0924857907000714',
  content13: 'http://www.sciencedirect.com/science/article/pii/S0090825810010620',
  content14: 'http://www.sciencedirect.com/science/article/pii/S1201971207000422',
  content15: 'http://www.sciencedirect.com/science/article/pii/S1040842809001243',
  content16: 'http://www.sciencedirect.com/science/article/pii/S1083879110009390',
  content17: 'http://www.sciencedirect.com/science/article/pii/S1083879111011232',
  content18: 'http://www.sciencedirect.com/science/article/pii/S0145212611005091',
  content19: 'http://www.sciencedirect.com/science/article/pii/S0924857908000502',
  content2: 'http://www.sciencedirect.com/science/article/pii/S0037196309000572',
  content20: 'http://www.sciencedirect.com/science/article/pii/S0735675710003864',
  content3: 'http://www.sciencedirect.com/science/article/pii/S0145212609004275',
  content4: 'http://www.sciencedirect.com/science/article/pii/S0883944110001620',
  content5: 'http://www.sciencedirect.com/science/article/pii/S0924857910004061',
  content6: 'http://www.sciencedirect.com/science/article/pii/S092485790800294X',
  content7: 'http://www.sciencedirect.com/science/article/pii/S0959804911000669',
  content8: 'http://www.sciencedirect.com/science/article/pii/S1040842810000776',
  content9: 'http://www.sciencedirect.com/science/article/pii/S0924857907000167'
}
